version: "2.4"

services:
  python:
    build:
      dockerfile: ./docker/Dockerfile-dev
      context: ./
    env_file:
      - .env_dev
    ports:
      - "8888:8888"
    command:
      jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='local_dev'
    volumes:
      - './data:/usr/src/app/data'
      - './code:/usr/src/app/code'
      - './notebooks:/usr/src/app/notebooks'
